apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp-container
        image: santoshhkumarr/sampleapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
